In [43]:
from dataloader import DataLoader
dataloader = DataLoader(base_path="./datasets")

In [44]:
DATASET_NAME = "rest15"

In [45]:
dataset = [] 
for ds_name in ["train", "test", "dev"]:
  dataset += dataloader.load_data(name=DATASET_NAME, data_type=ds_name)
len(dataset)

1580

In [46]:
import random 
import numpy as np
from sklearn.preprocessing import MultiLabelBinarizer
from iterstrat.ml_stratifiers import MultilabelStratifiedKFold

def random_cross_validation_split(data, seed=42):
    categories = [[el["aspect_category"] for el in an["aspects"]] for an in data]

    mlb = MultiLabelBinarizer()
    Y = mlb.fit_transform(categories)
    print(Y)
    category_names = mlb.classes_

    n_splits = 5
    mskf = MultilabelStratifiedKFold(n_splits=n_splits, shuffle=True, random_state=seed)
    
    splits = []
    for train_index, test_index in mskf.split(np.zeros(len(Y)), Y):
       splits.append((train_index, test_index))
    
    
    return splits


In [47]:
splits = random_cross_validation_split(dataset)
categories = [[el["aspect_category"] for el in an["aspects"]] for an in dataset]

[[1 0 0 ... 1 0 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [48]:
mlb = MultiLabelBinarizer()
Y = mlb.fit_transform(categories)
category_names = mlb.classes_

In [49]:
for i, (train_idx, test_idx) in enumerate(splits):
    print(f"Split {i + 1}:\n")

    test_counts = np.sum(Y[test_idx], axis=0)
    
    print("\nTest Data Category Counts:")
    for category, count in zip(category_names, test_counts):
        print(f"{category}: {count}")
    
    print("\n" + "-"*40 + "\n")

Split 1:


Test Data Category Counts:
ambience general: 43
drinks prices: 4
drinks quality: 9
drinks style_options: 5
food general: 0
food prices: 15
food quality: 132
food style_options: 22
location general: 5
restaurant general: 73
restaurant miscellaneous: 17
restaurant prices: 15
service general: 74

----------------------------------------

Split 2:


Test Data Category Counts:
ambience general: 43
drinks prices: 4
drinks quality: 9
drinks style_options: 6
food general: 0
food prices: 15
food quality: 131
food style_options: 22
location general: 5
restaurant general: 73
restaurant miscellaneous: 17
restaurant prices: 16
service general: 74

----------------------------------------

Split 3:


Test Data Category Counts:
ambience general: 43
drinks prices: 3
drinks quality: 8
drinks style_options: 6
food general: 1
food prices: 15
food quality: 132
food style_options: 22
location general: 6
restaurant general: 73
restaurant miscellaneous: 17
restaurant prices: 15
service general: 74